### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by bjartebore** [ForgeRock/forgerock-android-sdk#359]
There is no way of sending the `Accept-Language` http with the REST requests. The SDK does not send the system default language nor provide a way of overriding the language.

**Comment by jeyanthanperiyasamy** [comment]
Hi ,
Can you you please refer this page , this will explain how to add custom headers via interceptor using ForgeRock SDK
https://backstage.forgerock.com/docs/sdks/latest/sdks/customize/how-to-customize-requests.html

For any future queries, Please open a Support Zendesk Ticket  with ForgeRock
